web/aurwebdj/api/urls.py
#!/usr/bin/env python3
from django.urls import path
from .views import RPCView

urlpatterns = [
    path('rpc/', RPCView.as_view(), name='rpc'),
]

web/aurwebdj/aurwebdj/urls.py
from django.contrib import admin
from django.urls import path

import home.urls
import api.urls
import packages.urls
import users.urls

urlpatterns = [
  *api.urls.urlpatterns,
  *users.urls.urlpatterns,
  *packages.urls.urlpatterns,
  *home.urls.urlpatterns,
]

web/aurwebdj/users/urls.py
#!/usr/bin/env python3
from django.urls import path
from .views import *

urlpatterns = [
  path("register/", RegisterView.as_view(), name="user_register"),
  path("login/", LoginView.as_view(), name="user_login"),
  path("logout/", LogoutView.as_view(), name="user_logout"),
  path("accounts/", AccountsView.as_view(), name="user_search"),
  path("update/", UpdateView.as_view(), name="update"),
  # path("account/<user>/comments/", UserCommentsView.as_view(), name="user_comments"),
  # account/<user>/update/ may be removed in favor of GET+POST account/<user>/edit/
  # path("account/<user>/update/" UserUpdateView.as_view(), name="user_update"),
  path("account/<username>/delete/", DeleteAccountView.as_view(), name="user_delete"),
  path("account/<username>/edit/", EditAccountView.as_view(), name="user_edit"),
  path("account/<username>/", AccountView.as_view(), name="user"),
  # path("tu/", TrustedUserView.as_view(), name="tu"),
]

web/aurwebdj/users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django_unixdatetimefield import UnixDateTimeField
User = get_user_model()

class AURAccountType(models.Model):
  name = models.CharField(max_length=32)

class AURUser(User):
  uid = models.IntegerField(default=1, primary_key=False)

  account_type = models.ForeignKey(AURAccountType,
      on_delete=models.CASCADE, related_name="users", primary_key=False)

  realname = models.CharField(max_length=255, default="")
  suspended = models.BooleanField(default=False)
  hide_email = models.BooleanField(default=False)

  reset_key = models.CharField(max_length=32, default="")

  lang_preference = models.CharField(max_length=6, default="en")
  
  tz = models.CharField(max_length=32, default="UTC")
  homepage = models.TextField(null=True, blank=True, default="")
  irc_nick = models.CharField(max_length=32, default="")
  pgp_key = models.CharField(max_length=40, null=True, blank=True)
  
  last_login_ip_address = models.CharField(max_length=45,
      null=True, blank=True)
  last_ssh_login = models.DateTimeField(null=True, blank=True)
  last_ssh_login_ip_address = models.CharField(max_length=45,
      null=True, blank=True)

  inactivity_ts = models.IntegerField(default=0)

  registered_at = models.DateTimeField(null=True, blank=True)

  comment_notify = models.BooleanField(default=True)
  update_notify = models.BooleanField(default=False)
  ownership_notify = models.BooleanField(default=True)

  indexes = [
    models.Index(fields=['uid',])
  ]

  # Custom autoincrement on uid
  def save(self, *args, **kwargs):
    if self._state.adding:
      last_id = AURUser.objects.all().aggregate(largest=models.Max('uid'))['largest']
      if last_id is not None:
        self.uid = last_id + 1
    super().save(*args, **kwargs)

  def voted(self, pkgbase):
    return PackageVote.objects.\
        filter(user=self).\
        filter(package_base=pkgbase).\
        exists()

class Ban(models.Model):
  ip_address = models.CharField(max_length=45, primary_key=True)
  banned_at = models.DateTimeField(default=timezone.now)

class APIRateLimit(models.Model):
  ip_address = models.CharField(max_length=45)
  requests = models.IntegerField(0)
  window_start = models.IntegerField(0)

  indexes = [
    models.Index(fields=['window_start',])
  ]

class Term(models.Model):
  description = models.CharField(max_length=255)
  url = models.CharField(max_length=8000)
  revision = models.IntegerField(default=1)

class AcceptedTerm(models.Model):
  user = models.ForeignKey(AURUser, on_delete=models.CASCADE,
      related_name="accepted_terms")
  term = models.ForeignKey(Term, on_delete=models.CASCADE,
      related_name="accepted")
  revision = models.IntegerField(default=0)

class SSHPubKey(models.Model):
  user = models.ForeignKey(AURUser, on_delete=models.CASCADE,
      related_name="ssh_keys", primary_key=False)
  fingerprint = models.CharField(max_length=44, primary_key=True)
  pub_key = models.CharField(max_length=4096)

# End of users.models

web/aurwebdj/users/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, get_user_model
from django.conf import settings
from django.utils import translation, timezone
from datetime import datetime
import pytz
import re

from helpers.timezone import get_timezones
from helpers.render import aur_render
from users.models import AURUser, AURAccountType

User = get_user_model()

# Set cached constants here
timezones = get_timezones()

class RegisterView(View):
  def get(self, request):
    return aur_render(request, "users/register.html", {
      "timezones": timezones
    })

  def post(self, request):
    error = None

    return aur_render(request, "users/register.html", {
      "message": "Successfully registered."
    })

class AccountView(View):
  def get(self, request, username):
    auruser = get_object_or_404(AURUser, username=username)
    return aur_render(request, "users/account.html", {
      "user": auruser
    })

class AccountsView(View):
  def denied(self, request):
    return aur_render(request, "access_denied.html", {
      "page_title": "Accounts",
      "msg": "You do not have permission to view this page."
    })

  def get(self, request):
    auruser = None
    if request.user.is_authenticated:
      auruser = AURUser.objects.filter(user_ptr=request.user)
    if auruser and auruser.exists():
      auruser = auruser[0]
    else:
      return self.denied(request)

    if auruser.account_type.name != "Trusted User" \
    and auruser.account_type.name != "Trusted User & Developer":
      return self.denied(request)

    return aur_render(request, "users/accounts.html")

  def post(self, request):
    return aur_render(request, "users/accounts.html")

class EditAccountView(View):
  def get(self, request, username):
    auruser = None
    current_auruser = None

    if AURUser.objects.filter(username=username).exists():
      auruser = AURUser.objects.get(username=username)
    if AURUser.objects.filter(user_ptr=request.user).exists():
      current_auruser = AURUser.objects.get(user_ptr=request.user)

    if not auruser:
      return aur_render(request, "404.html")

    is_tu = current_auruser.account_type.name == "Trusted User" \
        or current_auruser.account_type.name == "Trusted User & Developer"

    if auruser != current_auruser and not is_tu:
      return aur_render(request, "access_denied.html", {
        "page_title": "Accounts"
      })

    return aur_render(request, "users/edit.html", {
      "user": auruser,
      "current_user": current_auruser
    })

class DeleteAccountView(View):
  def get(self, request, username):
    return aur_render(request, "users/delete.html")

class UpdateView(View):
  def post(self, request):
    _next = None
    if "next" in request.POST:
      _next = request.POST["next"]

    if "setlang" in request.POST:
      if request.user.is_authenticated:
        auruser = AURUser.objects.get(user_ptr=request.user)
        auruser.lang_preference = request.POST["setlang"]
        auruser.save()
      response = HttpResponseRedirect(_next if _next else "/")
      request.session[translation.LANGUAGE_SESSION_KEY] = request.POST["setlang"]
      response.set_cookie(settings.LANGUAGE_COOKIE_NAME, request.POST["setlang"])
      return response

    return HttpResponseRedirect(_next if _next else "/")

class LoginView(View):
  def get(self, request):
    return aur_render(request, "users/login.html")

  def post(self, request):
    username = request.POST.get("user", None)
    passwd = request.POST.get("passwd", None)
    
    errors = []

    if not username or not passwd:
      return self.render(request)

    if not AURUser.objects.filter(username=username).exists():
      errors.append("Bad username or password.")
      return self.render(request, errors)

    auruser = AURUser.objects.get(username=username)

    if not auruser.check_password(passwd):
      errors.append("Bad username or password.")
      return self.render(request, errors)

    login(request, auruser)

    return HttpResponseRedirect("/")

  def render(self, request, errors=None):
    if errors:
      return aur_render(request, "users/login.html", { "errors": errors })
    return aur_render(request, "users/login.html")

class LogoutView(View):
  def get(self, request):
    if request.user.is_authenticated:
      logout(request)
    return HttpResponseRedirect("/")

# Create your views here.
class UserSearchView(View):
  def get(self, request):
    return render(request, "users/index.html")

web/aurwebdj/users/templates/users/account.html
{% extends "aurbase.html" %}
{% load static %}
{% load i18n %}
{% load trans_args %}
{% load user_tags %}

{% block ptitle %}{{ user.username }}{% endblock %}

{% block content %}
<div class="box">

  <h2>{% trans "Accounts" %}</h2>
  <table class="arch-bio-entry">
    <tbody>
      <tr>
        <td>
          <h3>{{ user.username }}</h3>
          <table class="bio">
            <tbody>
              <tr><th>{% trans "Username" %}:</th><td>{{ user.username }}</td></tr>
              <tr><th>{% trans "Account Type" %}:</th><td>{{ user.account_type.name }}</td></tr>
              {% if not user.hide_email %}
              <tr><th>{% trans "Email Address" %}:</th><td><a href="mailto:{{ user.email|urlencode }}">{{ user.email }}</a></td></tr>
              {% endif %}
              <tr><th>{% trans "Homepage" %}:</th><td>{{ user.homepage }}</td></tr>
              <tr><th>{% trans "IRC Nick" %}:</th><td>{{ user.irc_nick }}</td></tr>
              <tr><th>{% trans "PGP Key Fingerprint" %}:</th><td>{{ user.pgp_key }}</td></tr>
              <tr><th>{% trans "Status" %}:</th><td>{% if user.is_active %}Active{% else %}Inactive{% endif %}</td></tr>
              <tr><th>{% trans "Registration date" %}:</th><td>{{ user.registered_at|date:"Y-m-d" }}</td></tr>
              <tr>
                <th>{% trans "Links" %}:</th>
                <td>
                  <ul>
                    <li><a href="/packages/?K={{ user.username|urlencode }}&SeB=m">View this user's packages</a></li>

                    <!-- If this user page is our own page, or we are a TU -->
                    {% if request.user|aur == user or request.user|is_tu %}
                    <li><a href="/account/{{ user.username|urlencode }}/edit/">Edit this user's account</a></li>
                    {% endif %}

                    <li><a href="/account/{{ user.username|urlencode }}/comments/">List this user's comments</a></li>
                  </ul>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>

</div>
{% endblock %}

web/aurwebdj/users/templates/users/accounts.html
{% extends "aurbase.html" %}
{% load static %}
{% load i18n %}
{% load trans_args %}
{% load user_tags %}

{% block ptitle %}Accounts{% endblock %}

{% block content %}
<div class="box">
  <h2>{% trans "Accounts" %}</h2>
  <p>{% trans "Use this form to search existing accounts." %}</p>

  <form action="/accounts/" method="post">
    <fieldset>
      <p>
        <label for="id_username">{% trans "Username" %}:</label>
        <input type="text" size="30" maxlength="64" name="U" id="id_username" />
      </p>

      <p>
        <label for="id_type">{% trans "Account Type" %}:</label>
        <select name="T" id="id_type">
          <option value="0">Any type</option>
          <option value="1">Normal User</option>
          <option value="2">Trusted User</option>
          <option value="3">Developer</option>
          <option value="4">Trusted User &amp; Developer</option>
        </select>
      </p>

      <p>
        <!-- Account suspended -->
        <label for="id_suspended">{% trans "Account Suspended" %}:</label>
        <input type="checkbox" name="S" id="id_suspended" />
      </p>

      <p>
        <!-- Email Address -->
        <label for="id_email">{% trans "Email Address" %}:</label>
        <input type="email" size="30" maxlength="64" name="E" id="id_email" />
      </p>

      <p>
        <!-- Real Name -->
        <label for="id_realname">{% trans "Real Name" %}:</label>
        <input type="text" size="30" maxlength="64" name="R" id="id_realname" />
      </p>

      <p>
        <!-- IRC Nick -->
        <label for="id_ircnick">{% trans "IRC Nick" %}:</label>
        <input type="text" size="30" maxlength="64" name="R" id="id_ircnick" />
      </p>

      <p>
        <label for="id_sortby">{% trans "Sort by" %}:</label>
        <select name="SB" id="id_sortby">
          <option value="u">Username</option>
          <option value="t">Account Type</option>
          <option value="r">Real Name</option>
          <option value="i">IRC Nick</option>
        </select>
        <!-- Sort By (SB) -->
      </p>

      <p>
        <!-- Search/Reset -->
        <label></label>
        <input type="submit" value="Search" />
        <input type="reset" value="Reset" />
      </p>

    </fieldset>
  </form>
</div>
{% endblock %}

web/aurwebdj/users/templates/users/delete.html
{% extends "aurbase.html" %}
{% load static %}
{% load i18n %}
{% load trans_args %}
{% load user_tags %}

{% block ptitle %}{% trans "Accounts" %}{% endblock %}

{% block content %}
<div class="box">
  <h2>{% trans "Accounts" %}</h2>
  {% with "<strong>"|add:user.username|add:"</strong>" as user_str %}
  <p>{% trans_args "You can use this form to permanently delete the AUR account {}.|"|add:user_str %}</p>
  {% endwith %}

  <p>{% trans_args "{}WARNING{}: This action cannot be undone.|<strong>|</strong>" %}</p>

  <form id="edit-profile-form" action="/account/{{ user.username|urlencode }}/delete/" method="post">
    <fieldset>
      {% csrf_token %}
      <p>
        <label class="confirmation">
          <input type="checkbox" name="confirm" value="1" />
          {% trans "Confirm deletion" %}
        </label>
      </p>
      <p>
        <input type="submit" class="button" value="Delete" />
      </p>
    </fieldset>
  </form>
</div>
{% endblock %}

web/aurwebdj/users/templates/users/edit.html
{% extends "aurbase.html" %}
{% load static %}
{% load i18n %}
{% load trans_args %}
{% load user_tags %}

{% block ptitle %}{% if user == current_user or request.user|is_tu %}Editing {{ user.username }}{% else %}Access Denied{% endif %}{% endblock %}

{% block content %}
<div class="box">

  <h2>{% trans "Accounts" %}</h2>
  <p>
  {% with user.username|urlencode as encoded_user %}

  {% with "Click {}here{} if you want to permanently delete this account.|<a href='/account/"|add:encoded_user|add:"/delete/'>|</a>" as perm_del %}
  {% trans_args perm_del %}
  {% endwith %}

  {% with "Click {}here{} for user details.|<a href='/account/"|add:encoded_user|add:"/'>|</a>" as user_page %}
  {% trans_args user_page %}
  {% endwith %}

  {% with "Click {}here{} to list the comments made by this account.|<a href='/account/"|add:encoded_user|add:"/comments/'>|</a>" as comment_page %}
  {% trans_args comment_page %}
  {% endwith %}

  {% endwith %}
  </p>

</div>
{% endblock %}

web/aurwebdj/users/templates/users/index.html
{% extends "aurbase.html" %}

{% block ptitle %}Accounts{% endblock %}

{% block content %}
<div>Home Page.</div>
{% endblock %}

web/aurwebdj/users/templates/users/login.html
{% extends "aurbase.html" %}
{% load i18n %}
{% load trans_args %}

{% block ptitle %}AUR {% trans "Login" %}{% endblock %}

{% block content %}
<div id="dev-login" class="box">
  <h2>AUR {% trans "Login" %}</h2>
  <form method="post" action="/login/">
    <fieldset>
      <legend>Enter login credentials</legend>

      {% if errors %}
      <ul class="errorlist">
        {% for error in errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}

      <p>
        <label for="id_username">User name or email address:</label>
        <input id="id_username" type="text" name="user" size="30" maxlength="254" autofocus="autofocus" />
      </p>
      <p>
        <label for="id_password">Password:</label>
        <input id="id_password" type="password" name="passwd" size="30" />
      </p>
      <p>
        <input type="checkbox" name="remember_me" id="id_remember_me" />
        <label for="id_remember_me">Remember me</label>
      </p>
      <p>
        <input type="submit" class="button" value="Login" />
        <a href="/passreset/">[Forgot Password]</a>
        <input id="id_referer" type="hidden" name="referer"
               value="https://aur.archlinux.org/login/" />
        {% csrf_token %}
      </p>
    </fieldset>
  </form>
</div>
{% endblock %}

web/aurwebdj/users/templates/users/register.html
{% extends "aurbase.html" %}
{% load i18n %}
{% load trans_args %}
{% load user_tags %}

{% block ptitle %}{% trans "Register" %}{% endblock %}

{% block content %}

<div class="box">
  <h2>{% trans "Register" %}</h2>
  <p>{% trans "Use this form to create an account." %}</p>

  <form id="edit-profile-form" method="post">
    <fieldset>
      <p>
        <label for="id_username">{% trans "Username" %}:</label>
        <input type="text" size="30" maxlength="16" name="U" id="id_username" /> (required)
      </p>
      <p>
        <em>{% trans "Your user name is the name you will use to login. It is visible to the general public, even if your account is inactive." %}</em>
      </p>

      <p>
        <label for="id_email">{% trans "Email Address" %}:</label>
        <input type="text" size="30" maxlength="254" name="E" id="id_email" /> (required)
      </p>

      <p>
        <em>{% trans "Please ensure you correctly entered your email address, otherwise you will be locked out." %}</em>
      </p>

      <p>
        <label for="id_hide">{% trans "Hide Email Address" %}:</label>
        <input type="checkbox" name="H" id="id_hide" />
      </p>

      <p>
        <label for="id_realname">{% trans "Real Name" %}:</label>
        <input type="text" size="30" maxlength="32" name="R" id="id_realname" />
      </p>

      <p>
        <label for="id_homepage">{% trans "Homepage" %}:</label>
        <input type="text" size="30" maxlength="32" name="HP" id="id_homepage" />
      </p>

      <p>
        <label for="id_irc">{% trans "IRC Nick" %}:</label>
        <input type="text" size="30" maxlength="32" name="I" id="id_irc" />
      </p>

      <p>
        <label for="id_pgp">{% trans "PGP Key Fingerprint" %}:</label>
        <input type="text" size="30" maxlength="32" name="K" id="id_pgp" />
      </p>

      <p>
        <label for="id_language">{% trans "Language" %}:</label>
        <select name="L" id="id_language">
          {% include "language_options.html" %}
        </select>
      </p>

      <p>
        <label for="id_timezone">{% trans "Timezone" %}:</label>
        <select name="TZ" id="id_timezone">
          {% for code, tz in timezones %}
          <option value="{{ tz }}"{% if tz == "UTC" %} selected="selected"{% endif %}>{{ code }} {{ tz }}</option>
          {% endfor %}
        </select>
      </p>
    </fieldset>

  </form>

</div>

{% endblock %}